# Generated by Django 3.2 on 2021-09-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('tractorName', models.CharField(max_length=1000)),
                ('implements', models.CharField(max_length=1000)),
            ],
        ),
    ]
