# Generated by Django 3.2 on 2021-09-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='implements',
        ),
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harrow', models.BooleanField(default=False)),
                ('cultivator', models.BooleanField(default=False)),
                ('rotavator', models.BooleanField(default=False)),
                ('plough', models.BooleanField(default=False)),
                ('paddy_thrasher', models.BooleanField(default=False)),
                ('dumping_trailer', models.BooleanField(default=False)),
                ('wheel_trailer', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.farmer')),
            ],
        ),
    ]
