# Generated by Django 3.2 on 2021-09-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210929_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implement',
            name='cultivator',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='implement',
            name='dumping_trailer',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='implement',
            name='harrow',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='implement',
            name='paddy_thrasher',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='implement',
            name='plough',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='implement',
            name='rotavator',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='implement',
            name='wheel_trailer',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
